- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportPostProcessor.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/Block.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/TextBlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocument.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocumentProvider.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/TemplateDocument.java
- geoide-viewer/modules/print-service/conf/templates/A4-staand.html
> 64 adapting printtemplate printrequest for grid

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportData.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportPostProcessor.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/TextBlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/TextBlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocument.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocumentProvider.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/TemplateDocument.java
- geoide-service/geoide-service-tms/src/main/java/nl/idgis/geoide/service/tms/TMSServiceType.java
- geoide-viewer/modules/print-service/public/test/grid.less
> changes to get the ReportComposer/Propcessor work with the new grid

- geoide-document-cache/src/main/java/nl/idgis/geoide/documentcache/Document.java
- geoide-document-cache/src/main/java/nl/idgis/geoide/documentcache/service/DelegatingStore.java
- geoide-document-cache/src/main/java/nl/idgis/geoide/documentcache/service/FileStore.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocument.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocumentProvider.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/TemplateDocument.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/TemplateDocumentProvider.java
- geoide-viewer/conf/application.conf
- geoide-viewer/modules/config/app/geoide/config/ControllerConfig.java
- geoide-viewer/modules/config/app/geoide/config/PrintServiceConfig.java
- geoide-viewer/modules/config/app/geoide/config/StreamConfig.java
- geoide-viewer/modules/mapview/app/assets/mapview/js/ViewerBase.js
- geoide-viewer/modules/print-service/app/controllers/printservice/JavaScript.java
- geoide-viewer/modules/print-service/app/controllers/printservice/Template.java
- geoide-viewer/modules/print-service/conf/printservice.routes
> 88 file store and delegating store

- geoide-document-cache/src/main/java/nl/idgis/geoide/documentcache/service/FileStore.java
- geoide-document-cache/src/test/java/nl/idgis/geoide/documentcache/service/TestFileStore.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocument.java
> 90 unit test filestore

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/BlockUtil.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockInfo.java
> new BlockUtil class with getGridWidth and getGridHeight methods

- geoide-viewer/app/assets/viewer/js/main.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/engine/DrawGeometry-ol3.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/engine/InteractionBase-ol3.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/engine/engine-ol3.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/DrawGeometry.js
> modifier shift for DrawGeometry interaction

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/BlockUtil.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockInfo.java
> take into account borderwidth when calculating bloack width

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/BlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/DateBlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/ScaleBarBlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/ScaleBarBlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/ScaleTextBlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/TextBlockInfo.java
- geoide-viewer/modules/toc/app/controllers/toc/TOC.java
> 43 scalebarcomposer

- geoide-print/src/main/java/nl/idgis/geoide/commons/print/service/HtmlPrintService.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportPostProcessor.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocument.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocumentProvider.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/TemplateDocument.java
> Print base url

- geoide-document-cache/pom.xml
- geoide-domain-test/pom.xml
- geoide-domain/pom.xml
- geoide-http-client/pom.xml
- geoide-layer/geoide-layer-common/pom.xml
- geoide-layer/geoide-layer-default/pom.xml
- geoide-layer/pom.xml
- geoide-map/pom.xml
- geoide-print/pom.xml
- geoide-service/geoide-service-common/pom.xml
- geoide-service/geoide-service-tms/pom.xml
- geoide-service/geoide-service-wfs/pom.xml
- geoide-service/geoide-service-wms/pom.xml
- geoide-service/pom.xml
- geoide-util/pom.xml
- geoide-viewer/project/Common.scala
- pom.xml
updated versions in Common.scala for play
> updated maven versions in pom's

- geoide-viewer/app/assets/viewer/js/main.js
- geoide-viewer/app/views/viewer/viewer.scala.html
- geoide-viewer/modules/mapview/app/assets/mapview/css/mapview.less
- geoide-viewer/modules/mapview/app/assets/mapview/js/Overlay.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/_EditableMixin.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/ModifyGeometry.js
Redlining features can be selected, edited and deleted.
Connects to #82
> Edit and delete redlining

- geoide-viewer/app/assets/viewer/js/main.js
- geoide-viewer/app/views/viewer/layout/html.scala.html
- geoide-viewer/modules/mapview/app/assets/mapview/js/Overlay.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/ViewerBase.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/ViewerOverlayMixin.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/_EditableMixin.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/ModifyGeometry.js
(text-) overlays are included when posting the viewer state for a report.
Connects to #82
> Overlays in report viewer state

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/BlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockInfo.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/render/OverlayRenderer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/render/SvgRenderer.java
> Added SVG overlay renderer to map block composer.

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/render/OverlayRenderer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/render/SvgRenderer.java
> Print text boxes

- geoide-viewer/modules/mapview/app/assets/mapview/js/Overlay.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/_EditableMixin.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/DrawText.js
> Redline text fixes

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/ReportComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/ScaleBarBlockComposer.java
> Changed the size of the scalebar on the print.

- geoide-viewer/test/IntegrationTest.java
> Fixed integration test.

- geoide-viewer/build.sbt
- geoide-viewer/modules/config/build.sbt
- geoide-viewer/modules/core/build.sbt
- geoide-viewer/modules/mapview/build.sbt
- geoide-viewer/modules/print-service/build.sbt
- geoide-viewer/modules/toc/build.sbt
> Configuration for publishing to Nexus.

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/blocks/MapBlockComposer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/render/OverlayRenderer.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/render/SvgRenderer.java
> 127 bug redlining in print

- geoide-app/src/main/resources/application.conf
- geoide-app/src/main/resources/logback.xml
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/featuretypes.json
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/layers.json
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/map-definition.json
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/maps.json
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/servicelayers.json
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/services.json
- geoide-config/geoide-config-http/pom.xml
- geoide-config/geoide-config-http/src/main/java/nl/idgis/geoide/commons/config/HttpConfig.java
- geoide-config/geoide-config-map/pom.xml
- geoide-config/geoide-config-map/src/main/java/nl/idgis/geoide/commons/config/LayerTypeConfig.java
- geoide-config/geoide-config-map/src/main/java/nl/idgis/geoide/commons/config/MapViewConfig.java
- geoide-config/geoide-config-map/src/main/java/nl/idgis/geoide/commons/config/ServiceTypeConfig.java
- geoide-config/geoide-config-print/pom.xml
- geoide-config/geoide-config-print/src/main/java/nl/idgis/geoide/commons/config/PrintConfig.java
- geoide-config/geoide-config-providers/pom.xml
- geoide-config/geoide-config-providers/src/main/java/nl/idgis/geoide/commons/config/ProviderConfig.java
- geoide-config/pom.xml
- geoide-main/pom.xml
- geoide-main/src/main/java/nl/idgis/geoide/commons/main/GeoideServiceMain.java
- geoide-util/src/main/java/nl/idgis/geoide/util/ConfigWrapper.java
- pom.xml
> 100 component config

- geoide-config/geoide-config-providers/src/main/java/nl/idgis/geoide/commons/config/ProviderConfig.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/ExternalizableJsonNode.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/MimeContentType.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/layer/LayerState.java
- geoide-layer/geoide-layer-default/src/main/java/nl/idgis/geoide/commons/layer/DefaultLayerType.java
- geoide-main/src/main/java/nl/idgis/geoide/commons/main/GeoideServiceMain.java
- geoide-ogc-client/pom.xml
- pom.xml
> Fixes for compatibility with geoide-web

- geoide-ogc-client/pom.xml
- geoide-viewer/modules/mapview/build.sbt
- version conflict 
- missing ol dependency
> build problems solved by fixing the config

- geoide-document-cache/src/main/java/nl/idgis/geoide/documentcache/service/FileStore.java
> Return no templates if the print templates directory doesn't exist

- geoide-main/src/main/java/nl/idgis/geoide/commons/main/GeoideServiceMain.java
> DefaultOverrides added for geoide-main configuration.

- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/report/TemplateDocument.java
- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocumentProvider.java
> TemplateDocument.Builder fixed, externalized getTemplates result.

- geoide-app/src/main/resources/application.conf
- geoide-config/geoide-config-print/src/main/java/nl/idgis/geoide/commons/config/PrintConfig.java
- geoide-document-cache/src/main/java/nl/idgis/geoide/documentcache/service/DefaultDocumentCache.java
- geoide-document-cache/src/test/java/nl/idgis/geoide/documentcache/service/TestDefaultDocumentCache.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/serializers/DocumentSerializer.java
- geoide-print/src/test/java/nl/idgis/geoide/commons/print/service/TestHtmlPrintService.java
- geoide-remote/pom.xml
- geoide-remote/src/main/java/nl/idgis/geoide/commons/remote/transport/AkkaTransport.java
- geoide-remote/src/main/java/nl/idgis/geoide/commons/remote/transport/RemoteMethodServerActor.java
- geoide-remote/src/main/java/nl/idgis/geoide/commons/remote/transport/TransportActor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/akka/serializers/StreamSerializer.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/AkkaSerializablePublisher.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/AkkaSerializableSubscriber.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/AkkaSerializableSubscriberActor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/AkkaStreamProcessor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/ByteStringPublisher.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/SerializablePublisher.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/SerializablePublisherSubscriptionActor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/StreamProcessor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/StreamSerializer.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/messages/SubscriberCancelled.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/messages/SubscriberComplete.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/messages/SubscriberError.java
- geoide-util/src/test/java/nl/idgis/geoide/util/streams/AkkaSerializablePublisherTest.java
- geoide-util/src/test/java/nl/idgis/geoide/util/streams/ByteStringPublisherTest.java
- geoide-viewer/conf/application.conf
- geoide-viewer/modules/print-service/app/controllers/printservice/Report.java
> Publisher serializable over Akka connection

- geoide-viewer/modules/mapview/build.sbt
- geoide-viewer/project/Common.scala
Connects to #139 
Connects to #140
> Added jts dependency for play projects -> solves bugs with getFeature

- geoide-remote/.gitignore
- geoide-remote/pom.xml
- geoide-remote/src/test/java/nl/idgis/geoide/commons/remote/transport/TestAkkaTransportRemote.java
- geoide-util/src/main/java/nl/idgis/geoide/util/akka/serializers/ByteStringSerializer.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/AkkaStreamProcessor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/ByteStringPublisher.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/ByteStringPublisherActor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/ByteStringSubscriptionActor.java
- geoide-util/src/main/java/nl/idgis/geoide/util/streams/SerializablePublisherSubscriptionActor.java
> Remote publisher test

- geoide-viewer/modules/core/app/assets/core/js/json-request.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/ViewerBase.js
- geoide-viewer/modules/print-service/app/controllers/printservice/Report.java
> JS report error reporting

- geoide-print/src/main/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocumentProvider.java
- geoide-print/src/test/java/nl/idgis/geoide/commons/report/template/HtmlTemplateDocumentProviderTest.java
> Testcases for documentprovider

- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/DrawGeometry.js
> DrawGeometry on start event passes feature

- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/ModifyGeometry.js
- geoide-viewer/project/Common.scala
bug fixed removeFeature in ModifyGeometry
> Update to 3.8.2

- geoide-viewer/modules/mapview/app/assets/mapview/js/engine/Engine.js
> ol.View.getResolutionForExtent doesnot exist anymore -> replaced by own

- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/DrawGeometry.js
> shiftKey in DrawGeometry should be lowercase

- geoide-config/geoide-config-providers/src/main/java/nl/idgis/geoide/commons/config/ProviderConfig.java
- geoide-map/src/main/java/nl/idgis/geoide/map/provider/JsonMapProviderBuilder.java
> Documentation for JsonMapProviderBuilder

- geoide-viewer/modules/mapview/app/assets/mapview/js/engine/Engine.js
Connects to IDgis/CRS2-develop#54
> create olMap with the default attribution control false

- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/FeatureQuery.java
- geoide-map/src/main/java/nl/idgis/geoide/map/DefaultMapQuery.java
- geoide-service/geoide-service-wfs/src/main/java/nl/idgis/geoide/service/wfs/actors/WFS.java
- geoide-viewer/modules/core/app/assets/core/js/map/Map.js
> #72 feature info with bbox

- geoide-app/pom.xml
- geoide-config/geoide-config-akka/pom.xml
- geoide-config/geoide-config-http/pom.xml
- geoide-config/geoide-config-map/pom.xml
- geoide-config/geoide-config-print/pom.xml
- geoide-config/geoide-config-providers/pom.xml
- geoide-config/pom.xml
- geoide-document-cache/pom.xml
- geoide-domain/pom.xml
- geoide-http-client/pom.xml
- geoide-layer/geoide-layer-common/pom.xml
- geoide-layer/geoide-layer-default/pom.xml
- geoide-layer/pom.xml
- geoide-main/pom.xml
- geoide-map/pom.xml
- geoide-ogc-client/pom.xml
- geoide-print/pom.xml
- geoide-remote/pom.xml
- geoide-service/geoide-service-common/pom.xml
- geoide-service/geoide-service-tms/pom.xml
- geoide-service/geoide-service-wfs/pom.xml
- geoide-service/geoide-service-wms/pom.xml
- geoide-service/pom.xml
- geoide-util/pom.xml
- geoide-viewer/modules/mapview/app/assets/mapview/js/ViewerOverlayMixin.js
- geoide-viewer/modules/mapview/app/assets/mapview/js/interaction/DrawGeometry.js
- geoide-viewer/project/Common.scala
- pom.xml
Setting version to 1.0.1-SNAPSHOT
> Release v1.0.0

- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/JsonFactory.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/MapDefinition.java
connects to IDgis/CRS2-develop#58
> removed mapprefix from mapmodel

- geoide-viewer/app/views/viewer/layout/html.scala.html
- geoide-viewer/build.sbt
- geoide-viewer/project/Common.scala
connects to IDgis/CRS2-develop#59
> dojo ipv dojo-base

- geoide-viewer/app/views/viewer/layout/html.scala.html
- geoide-viewer/build.sbt
- geoide-viewer/project/Common.scala
connects to IDgis/Crs2-develop#59
> ipv complete dojo werken met dojo-base uit het nl.idgis.webjars package

- geoide-layer/geoide-layer-default/src/main/java/nl/idgis/geoide/commons/layer/toc/TOCdefaultLayerTypeTrait.java
connects to IDgis/CRS2-develop#60
> TocItem getSymbol werkte niet vanwege onterecht uit gecommentarieerde

- geoide-app/pom.xml
- geoide-config/geoide-config-akka/pom.xml
- geoide-config/geoide-config-http/pom.xml
- geoide-config/geoide-config-map/pom.xml
- geoide-config/geoide-config-print/pom.xml
- geoide-config/geoide-config-providers/pom.xml
- geoide-config/pom.xml
- geoide-document-cache/pom.xml
- geoide-domain/pom.xml
- geoide-http-client/pom.xml
- geoide-layer/geoide-layer-common/pom.xml
- geoide-layer/geoide-layer-default/pom.xml
- geoide-layer/pom.xml
- geoide-main/pom.xml
- geoide-map/pom.xml
- geoide-ogc-client/pom.xml
- geoide-print/pom.xml
- geoide-remote/pom.xml
- geoide-service/geoide-service-common/pom.xml
- geoide-service/geoide-service-tms/pom.xml
- geoide-service/geoide-service-wfs/pom.xml
- geoide-service/geoide-service-wms/pom.xml
- geoide-service/pom.xml
- geoide-util/pom.xml
- geoide-viewer/app/views/toc/toc.scala.html
- geoide-viewer/project/Common.scala
- pom.xml
> setting version to 1.0.4-SNAPSHOT

- geoide-viewer/modules/mapview/app/assets/mapview/js/engine/Engine.js
solves problem with double transparent parameter in getMap request
> added function capitalizeParams(params)

- build.gradle
> new SNAPSHOT version

- build.gradle
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/maps.json
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/querydescriptions.json
- geoide-app/src/main/resources/nl/idgis/geoide/commons/config/map/searchtemplates.json
- geoide-config/geoide-config-map/src/main/java/nl/idgis/geoide/commons/config/MapConfig.java
- geoide-config/geoide-config-providers/src/main/java/nl/idgis/geoide/commons/config/ProviderConfig.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/JsonFactory.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/MapDefinition.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/QueryDescription.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/SearchTemplate.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/api/MapProviderApi.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/provider/MapProvider.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/provider/QueryDescriptionProvider.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/provider/SearchTemplateProvider.java
- geoide-domain/src/main/java/nl/idgis/geoide/commons/domain/provider/StaticMapProvider.java
- geoide-map/src/main/java/nl/idgis/geoide/map/provider/JsonMapProviderBuilder.java
- geoide-map/src/test/java/nl/idgis/geoide/map/provider/JsonMapProviderBuilderTest.java
- geoide-map/src/test/resources/nl/idgis/geoide/map/provider/test-map.json
- geoide-viewer/app/assets/viewer/js/main.js
- geoide-viewer/app/controllers/viewer/Viewer.java
- geoide-viewer/app/views/viewer/layout/html.scala.html
- geoide-viewer/app/views/viewer/viewer.scala.html
- geoide-viewer/conf/viewer.routes
- geoide-viewer/modules/core/app/assets/core/js/map/Map.js
- geoide-viewer/modules/core/app/assets/core/js/map/MapBehaviour.js
- geoide-viewer/modules/core/app/assets/core/js/search/Search.js
- geoide-viewer/modules/core/app/controllers/core/MapConfiguration.java
- geoide-viewer/modules/mapview/app/assets/mapview/js/ViewerBase.js
> Query descriptions -> search templates

- geoide-main/src/main/java/nl/idgis/geoide/commons/main/GeoideServiceMain.java
Reverts IDgis/geoide-commons#295
Dit bleek niet de juiste plek voor deze code zie: IDgis/geoide-vfp#6
> Revert "Add retry mechanism to main"
